# Sequential API

In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
from tensorflow.keras import layers

In [4]:
model = keras.Sequential([
    layers.Dense(1024, input_dim=64),
    layers.Activation('relu'),
    layers.Dense(256),
    layers.Activation('relu'),
    layers.Dense(10),
    layers.Activation('softmax')
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
    )

In [8]:
# create toy data

data = np.random.random((2000, 64))
labels = np.random.random((2000, 10))

val_data = np.random.random((500, 64))
val_labels = np.random.random((500, 10))

test_data = np.random.random((500, 64))
test_labels = np.random.random((500, 10))

In [12]:
model.fit(data, 
          labels, 
          epochs=10, 
          batch_size=50,
          validation_data=(val_data, val_labels)
         )

Epoch 1/10
40/40 [==============================] - 0s 11ms/step - loss: 8666.6240 - accuracy: 0.0960 - val_loss: 9428.1260 - val_accuracy: 0.1020
Epoch 2/10
40/40 [==============================] - 0s 6ms/step - loss: 9135.3896 - accuracy: 0.0975 - val_loss: 8992.9219 - val_accuracy: 0.0980
Epoch 3/10
40/40 [==============================] - 0s 6ms/step - loss: 11083.7324 - accuracy: 0.1090 - val_loss: 12305.4160 - val_accuracy: 0.1140
Epoch 4/10
40/40 [==============================] - 0s 6ms/step - loss: 12269.0830 - accuracy: 0.0950 - val_loss: 13979.0146 - val_accuracy: 0.1200
Epoch 5/10
40/40 [==============================] - 0s 6ms/step - loss: 17520.0723 - accuracy: 0.0895 - val_loss: 18574.0898 - val_accuracy: 0.1140
Epoch 6/10
40/40 [==============================] - 0s 6ms/step - loss: 16644.1562 - accuracy: 0.1075 - val_loss: 13319.4922 - val_accuracy: 0.0940
Epoch 7/10
40/40 [==============================] - 0s 6ms/step - loss: 18804.5684 - accuracy: 0.0935 - val_loss: 2

In [13]:
model.evaluate(data, labels, batch_size=50)

40/40 [==============================] - 0s 3ms/step - loss: 23941.1367 - accuracy: 0.0870


[23941.13671875, 0.08699999749660492]

In [ ]:
result = model.predict(data, batch_size=50)
result

# Functional API

In [25]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import models

In [26]:
mnist = keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [27]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [31]:
inputs = keras.Input(shape=(28, 28))
flatten = layers.Flatten()
dense_layer = layers.Dense(50, activation='relu')

flatten_output = flatten(inputs)
dense_output = dense_layer(flatten_output)
predictions = layers.Dense(10, activation='softmax')(dense_output)
model = keras.Model(inputs=inputs, outputs=predictions)
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 28, 28)]          0         
                                                                 
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_8 (Dense)             (None, 50)                39250     
                                                                 
 dense_9 (Dense)             (None, 10)                510       
                                                                 
Total params: 39,760
Trainable params: 39,760
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.compile(
    optimizer="sgd",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
    )

model.fit(
    X_train, 
    y_train,
    validation_data=(X_train, y_train),
    epochs=10
    )

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 16.5755 - accuracy: 0.2182 - val_loss: 2.0345 - val_accuracy: 0.2076
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 2.0638 - accuracy: 0.2031 - val_loss: 2.0304 - val_accuracy: 0.2037
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 2.0158 - accuracy: 0.2185 - val_loss: 1.9630 - val_accuracy: 0.2380
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 1.9969 - accuracy: 0.2383 - val_loss: 1.9663 - val_accuracy: 0.2286
Epoch 5/10
1875/1875 [==============================] - 6s 3ms/step - loss: 2.0251 - accuracy: 0.2262 - val_loss: 2.1834 - val_accuracy: 0.1627
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 2.1332 - accuracy: 0.1938 - val_loss: 2.0904 - val_accuracy: 0.1984
Epoch 7/10
1875/1875 [==============================] - 6s 3ms/step - loss: 2.1163 - accuracy: 0.1979 - val_loss: 2.0697 - val_accuracy

In [37]:
model.evaluate(X_test, y_test, batch_size=50)

200/200 [==============================] - 1s 4ms/step - loss: 2.1320 - accuracy: 0.1752


[2.132014751434326, 0.17520000040531158]

## House data

In [7]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import models

In [8]:
house_data_inputs = layers.Input(shape=(128,), name="house_data")
x1 = layers.Dense(64, activation="relu")(house_data_inputs)
block_1_output = layers.Dense(32, activation="relu")(x1)

In [9]:
house_pic_inputs = layers.Input(shape=(128, 128, 3))
x = layers.Conv2D(64, 3, activation="relu", padding="same")(house_pic_inputs)
x = layers.Conv2D(64, 3, activation="relu", padding="same")(x)
block_2_output = layers.Flatten()(x)

In [10]:
x = layers.concatenate([block_1_output, block_2_output])
price_pred = layers.Dense(1, name="price", activation="relu")(x)
time_elapsed_price = layers.Dense(2, name="elapsed_time", activation="softmax")(x)

In [11]:
model = keras.Model(
    [house_data_inputs, house_pic_inputs],
    [price_pred, time_elapsed_price],
    name="house_price_prediction"
    )

## Extracting reusing layers

In [15]:
resnet = keras.applications.resnet.ResNet50()

In [16]:
intermediate_layers = [layer.output for layer in resnet.layers]

In [18]:
feature_layers = intermediate_layers[:-2]

In [19]:
feat_extaction_model = keras.Model(inputs=resnet.input, outputs=feature_layers)

# Preprocessing layers

In [22]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator, pad_sequences, skipgrams, make_sampling_table
from tensorflow.keras.preprocessing.text import text_to_word_sequence, one_hot, hashing_trick, Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [23]:
series = np.array([i for i in range(10)])
series

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
generator = TimeseriesGenerator(
    data=series,
    targets=series,
    length=5,
    batch_size=1,
    shuffle=False,
    reverse=False
    )

In [40]:
for i in range(len(generator)):
    x, y = generator[i]
    print(f"{x} -> {y}")

[[0 1 2 3 4]] -> [5]
[[1 2 3 4 5]] -> [6]
[[2 3 4 5 6]] -> [7]
[[3 4 5 6 7]] -> [8]
[[4 5 6 7 8]] -> [9]


In [41]:
model = Sequential()
model.add(Dense(10, activation="relu", input_dim=5))
model.add(Dense(1))
model.compile(optimizer="adam", loss="mse")

In [42]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 10)                60        
                                                                 
 dense_7 (Dense)             (None, 1)                 11        
                                                                 
Total params: 71
Trainable params: 71
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(generator, epochs=100)

In [47]:
model.predict([[3 ,4, 5, 8, 9]])

1/1 [==============================] - 0s 80ms/step


array([[10.964103]], dtype=float32)

In [48]:
sentences = [["What", "do", "you", "like", "?"],
 ["I", "like", "basket-ball", "!"],
 ["And", "you", "?"],
 ["I", "like", "coconut", "and", "apple"]]

In [53]:
text_set = set(np.concatenate(sentences))
vocab_to_int = dict(zip(text_set, range(len(text_set))))
int_to_vocab = {vocab_to_int[word]: word for word in vocab_to_int.keys()}

In [54]:
encoded_sentences = list()
for sentence in sentences:
    encoded_sentence = [vocab_to_int[word] for word in sentence]
    encoded_sentences.append(encoded_sentence)

In [60]:
encoded_sentences

[[5, 6, 10, 3, 11], [2, 3, 1, 9], [7, 10, 11], [2, 3, 4, 8, 0]]

In [61]:
pad_sequences(encoded_sentences, maxlen=7, truncating="post")

array([[ 0,  0,  5,  6, 10,  3, 11],
       [ 0,  0,  0,  2,  3,  1,  9],
       [ 0,  0,  0,  0,  7, 10, 11],
       [ 0,  0,  2,  3,  4,  8,  0]])

## Skip Grams

In [62]:
sentence = "I like coconut and apple"
encoded_sentence = [vocab_to_int[word] for word in sentence.split()]
vocabulary_size = len(encoded_sentence)

In [63]:
pairs, labels = skipgrams(encoded_sentence,
                         vocabulary_size,
                         window_size=1,
                         negative_samples=0)

In [67]:
for i in range(len(pairs)):
    print(f"{int_to_vocab[pairs[i][0]]}, {int_to_vocab[pairs[i][1]]} -> {labels[i]}")

like, I -> 1
coconut, and -> 1
coconut, like -> 1
like, coconut -> 1
I, like -> 1
and, coconut -> 1


## Text preprocessing

### Split text to word sequence

In [68]:
sentence = "I like coconut, I like apple"

text_to_word_sequence(sentence, lower=False)

['I', 'like', 'coconut', 'I', 'like', 'apple']

In [70]:
text_to_word_sequence(sentence, lower=True, filters=[])

['i', 'like', 'coconut,', 'i', 'like', 'apple']

### Tokenizer

In [71]:
sentences = [["What", "do", "you", "like", "?"],
 ["I", "like", "basket-ball", "!"],
 ["And", "you", "?"],
 ["I", "like", "coconut", "and", "apple"]]

In [72]:
t = Tokenizer()
t.fit_on_texts(sentences)

In [74]:
t.word_counts

OrderedDict([('what', 1),
             ('do', 1),
             ('you', 2),
             ('like', 3),
             ('?', 2),
             ('i', 2),
             ('basket-ball', 1),
             ('!', 1),
             ('and', 2),
             ('coconut', 1),
             ('apple', 1)])

## Image Preprocessing

In [75]:
(x_cifar10_train, y_cifar10_train), (x_cifar10_test, y_cifar10_test) = keras.datasets.cifar10.load_data()

170498071/170498071 [==============================] - 46s 0us/step


In [78]:
datagen = keras.preprocessing.image.ImageDataGenerator(rotation_range=15,
                                                      width_shift_range=3,
                                                      height_shift_range=3,
                                                      horizontal_flip=True)

In [80]:
it = datagen.flow(x_cifar10_train, y_cifar10_train, batch_size=32)

In [99]:
model = keras.Sequential([
        layers.Conv2D(filters=32, kernel_size=3, padding="same", activation="relu", input_shape=[32, 32, 3]),
        layers.Conv2D(filters=32, kernel_size=3, padding="same", activation="relu"),
        layers.MaxPool2D(pool_size=2),
        layers.Conv2D(filters=64, kernel_size=3, padding="same", activation="relu"),
        layers.Conv2D(filters=64, kernel_size=3, padding="same", activation="relu"),
        layers.MaxPool2D(pool_size=2),
        layers.Flatten(),
        layers.Dense(128, activation="relu"),
        layers.Dense(10, activation="softmax")
])

In [83]:
model.compile(loss="sparse_categorical_crossentropy",
             optimizer=keras.optimizers.SGD(learning_rate=0.01),
             metrics=["accuracy"])

In [ ]:
history = model.fit(it,
                   epochs=10,
                   steps_per_epoch=len(x_cifar10_train)/32,
                   validation_data=(x_cifar10_test, y_cifar10_test))

In [96]:
inputs = keras.Input(shape=(32, 32, 3))
flatten_layer = layers.Flatten()
dense_layer = layers.Dense(128, activation="relu")
conv = layers.Conv2D(32, 3, activation="relu", padding="same")
conv2 = layers.Conv2D(64, 3, activation="relu", padding="same")
maxpool = layers.MaxPool2D(pool_size=2)

x = layers.Conv2D(32, 3, activation="relu", padding="same")(inputs)
x = conv(x)
m = maxpool(x)
x = conv2(m)
x = conv2(x)
m = maxpool(m)
output = flatten_layer(m)
dense_output = dense_layer(output)
prediction = layers.Dense(10, activation="softmax")(dense_output)

In [97]:
model = keras.Model(inputs=inputs, outputs=prediction)

In [98]:
model.summary()

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_10 (InputLayer)          [(None, 32, 32, 3)]  0           []                               
                                                                                                  
 conv2d_20 (Conv2D)             (None, 32, 32, 32)   896         ['input_10[0][0]']               
                                                                                                  
 conv2d_18 (Conv2D)             (None, 32, 32, 32)   9248        ['conv2d_20[0][0]']              
                                                                                                  
 max_pooling2d_8 (MaxPooling2D)  multiple            0           ['conv2d_18[0][0]',              
                                                                  'max_pooling2d_8[0][0]']  

In [ ]:
model.compile(loss="sparse_categorical_crossentropy",
             optimizer=keras.optimizers.SGD(learning_rate=0.01),
             metrics=["accuracy"])

history = model.fit(it,
                   epochs=10,
                   steps_per_epoch=len(x_cifar10_train)/32,
                   validation_data=(x_cifar10_test, y_cifar10_test))